### ISSUE TITLE
Request to bring back horizontal line effect in novelist scheme

### ISSUE THREAD

**Issue by dolores824** [Bluemoondragon07/chime-theme#2]
The chime is so incredibly beautiful and well-designed. The variety of color schemes is a real highlight and I've been thoroughly enjoying experimenting with them. But I just noticed that the horizontal line effect that was previously present in the novelist scheme has been removed in the latest update. I was wondering if it would be possible to bring this feature back as it added a unique touch to the scheme and complemented it well. Thank you for considering the request.

**Comment by Bluemoondragon07** [comment]
I'm glad you've been enjoying my theme! I'll change the novelist divider back and update the theme sometime tomorrow--I'll let you know in a reply here when I finish. I removed the special divider for novelist because it wasn't rendering properly on mobile, but now that I know how to target mobile specifically in CSS I think I'll have it show up normally on desktop and be a normal divider on mobile.

**Comment by dolores824** [comment]
Thank you so much for your prompt response and for your hard work on the theme. I really appreciate it! I am excited to see the updates.

**Comment by Bluemoondragon07** [comment]
The novelist divider has been added back in the latest update! Thank you for bringing it up, too. I am also very fond of the divider and nearly forgot that I removed it in the first place.
